name: Sauce Connect Tunnel

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  connect_tunnel:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Start Sauce Connect Tunnel
        uses: saucelabs/sauce-connect-action@v2
        with:
          username: ${{ secrets.SAUCE_USERNAME }}
          accessKey: ${{ secrets.SAUCE_ACCESS_KEY }}
          tunnelName: github-action-tunnel
          configFile: .github/workflows/sc-config.yaml

      - name: Run tests
        run: |
          # Add your test commands here
          npm test

      - name: Stop Sauce Connect Tunnel
        uses: saucelabs/sauce-connect-action@v2
        with:
          username: ${{ secrets.SAUCE_USERNAME }}
          accessKey: ${{ secrets.SAUCE_ACCESS_KEY }}
          tunnelName: github-action-tunnel
          stop: true
