name: In Progress Config

on: workflow_dispatch

jobs:
  start_sc_api_tunnel:
    runs-on: ubuntu-latest
    name: Start API Testing Tunnel
    steps:
      - uses: actions/checkout@v3
      - uses: saucelabs/sauce-connect-action@v2
        with:
          username: '${{ secrets.SAUCE_USERNAME }}'
          accessKey: '${{ secrets.SAUCE_ACCESS_KEY }}'
          region: us-west
          tunnelName: test_tunnel_name
          configFile: ${{ github.workspace }}/sc-configuration/config.yaml

    # runs-on: ubuntu-latest
    # steps:
    #   - name: Checkout
    #     uses: actions/checkout@v3
    #     with:
    #       path: api_branch

    #   - name: Action Test
    #     uses: saucelabs/sauce-connect-action@v2
    #     with:
    #       username: '${{ secrets.SAUCE_USERNAME }}'
    #       accessKey: '${{ secrets.SAUCE_ACCESS_KEY }}'
    #       region: us-west
    #       tunnelName: test_tunnel_name
    #       configFile: ${{ github.workspace }}/sc-configuration/config.yaml
